name: Test Job
on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          
      - name: Install module
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test scraping
        run: |
          python shopify.py -p p_enji.csv -o o_enji.csv https://enji.co.id
          python shopify.py -p p_etcetera.csv -o o_etcetera.csv https://etcetera.co.id
          python shopify.py -p p_geela.csv -o o_geela.csv https://geela.id
          python shopify.py -p p_kami.csv -o o_kami.csv https://kamiidea.com
          python shopify.py -p p_palomino.csv -o o_palomino.csv https://palominobag.com
          python shopify.py -p p_purukambera.csv -o o_purukambera.csv https://purukambera.com

      - name: File checking
        run: |
          for file in $(ls | grep -E "p_.+\.csv$"); do
            wc -l $file
            tail -n 2 $file >> test.csv
          done;
          cat test.csv

