name: Test Job
on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          
      - name: Install module
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test crawling
        run: |
          python shopify.py -c crawl -i https://enji.co.id enji.txt
          python shopify.py -c crawl -i https://etcetera.co.id etcetera.txt
          python shopify.py -c crawl -i https://kamiidea.com kami.txt
          python shopify.py -c crawl -i https://palominobag.com palomino.txt
          python shopify.py -c crawl -i https://purukambera.com purukambera.txt

      - name: File checking
        run: |
          wc -l enji.txt && head -n 2 enji.txt > test.txt
          wc -l etcetera.txt && head -n 2 etcetera.txt >> test.txt
          wc -l kami.txt && head -n 2 kami.txt >> test.txt
          wc -l palomino.txt && head -n 2 palomino.txt >> test.txt
          wc -l purukambera.txt && head -n 2 purukambera.txt >> test.txt
          cat test.txt

      - name: Test scraping
        run: |
          python shopify.py -c scrape -i test.txt test.json
          cat test.json | jq
